### ISSUE TITLE
Regression Tests Fail

### ISSUE THREAD

**Issue by ftc** [cuplv/FixrGraphExtractor#106]
This seems to fail on older versions of the code as well so I think it may be a configuration issue on my machine.

Steps to reproduce:

- check out develop branch
- run `sbt test`

observed behavior:
-------------------
TestBug058, TestBug053, and TestBug051 fail.  All fail when trying to load java.* classes.

In the test TestBug058 the following exception is thrown:

```
Error: Failed to load java.lang.CharSequence.
java.lang.Error: Error: Failed to load java.lang.CharSequence.
	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:109)
	at soot.JastAddJ.Program.getCompilationUnit(Program.java:844)
	at soot.JastAddJ.Program.getLibCompilationUnit_compute(Program.java:1517)
	at soot.JastAddJ.Program.getLibCompilationUnit(Program.java:1500)
	at soot.JastAddJ.Program.lookupLibType_compute(Program.java:1465)
	at soot.JastAddJ.Program.lookupLibType(Program.java:1433)
	at soot.JastAddJ.Program.lookupType_compute(Program.java:1412)
	at soot.JastAddJ.Program.lookupType(Program.java:1393)
	at soot.JastAddJ.Program.Define_TypeDecl_lookupType(Program.java:1981)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:1657)
	at soot.JastAddJ.Expr.lookupType(Expr.java:1186)
	at soot.JastAddJ.TypeAccess.decls_compute(TypeAccess.java:425)
	at soot.JastAddJ.TypeAccess.decls(TypeAccess.java:414)
	at soot.JastAddJ.TypeAccess.refined_TypeScopePropagation_TypeAccess_decl(TypeAccess.java:387)
	at soot.JastAddJ.TypeAccess.decl_compute(TypeAccess.java:460)
	at soot.JastAddJ.TypeAccess.decl(TypeAccess.java:452)
	at soot.JastAddJ.TypeAccess.type_compute(TypeAccess.java:590)
	at soot.JastAddJ.TypeAccess.type(TypeAccess.java:583)
	at soot.JastAddJ.ParameterDeclaration.type_compute(ParameterDeclaration.java:479)
	at soot.JastAddJ.ParameterDeclaration.type(ParameterDeclaration.java:472)
	at soot.JastAddJ.MethodDecl.signature_compute(MethodDecl.java:1503)
	at soot.JastAddJ.MethodDecl.signature(MethodDecl.java:1488)
	at soot.JastAddJ.TypeDecl.localMethodsSignatureMap_compute(TypeDecl.java:2683)
	at soot.JastAddJ.TypeDecl.localMethodsSignatureMap(TypeDecl.java:2669)
	at soot.JastAddJ.ClassDecl.methodsSignatureMap_compute(ClassDecl.java:1102)
	at soot.JastAddJ.ClassDecl.methodsSignatureMap(ClassDecl.java:1094)
	at soot.JastAddJ.TypeDecl$2.<init>(TypeDecl.java:513)
	at soot.JastAddJ.TypeDecl.methodsIterator(TypeDecl.java:512)
	at soot.JastAddJ.ClassDecl.methodsSignatureMap_compute(ClassDecl.java:1104)
	at soot.JastAddJ.ClassDecl.methodsSignatureMap(ClassDecl.java:1094)
	at soot.JastAddJ.TypeDecl$2.<init>(TypeDecl.java:513)
	at soot.JastAddJ.TypeDecl.methodsIterator(TypeDecl.java:512)
	at soot.JastAddJ.TypeDecl.methodsNameMap_compute(TypeDecl.java:2619)
	at soot.JastAddJ.TypeDecl.methodsNameMap(TypeDecl.java:2608)
	at soot.JastAddJ.TypeDecl.memberMethods(TypeDecl.java:2578)
	at soot.JastAddJ.AbstractDot.Define_Collection_lookupMethod(AbstractDot.java:766)
	at soot.JastAddJ.Expr.lookupMethod(Expr.java:1032)
	at soot.JastAddJ.MethodAccess.decls_compute(MethodAccess.java:1094)
	at soot.JastAddJ.MethodAccess.decls(MethodAccess.java:1086)
	at soot.JastAddJ.MethodAccess.decl_compute(MethodAccess.java:1128)
	at soot.JastAddJ.MethodAccess.decl(MethodAccess.java:1120)
	at soot.JastAddJ.MethodAccess.nameCheck(MethodAccess.java:206)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1283)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.ASTNode.collectErrors(ASTNode.java:1292)
	at soot.JastAddJ.CompilationUnit.errorCheck(CompilationUnit.java:178)
	at soot.JastAddInitialResolver.formAst(JastAddInitialResolver.java:67)
	at soot.JavaClassSource.resolve(JavaClassSource.java:66)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:240)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:214)
	at soot.SootResolver.bringToSignatures(SootResolver.java:279)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:172)
	at soot.SootResolver.resolveClass(SootResolver.java:134)
	at soot.Scene.loadClass(Scene.java:942)
	at soot.Scene.loadClassAndSupport(Scene.java:927)
	at soot.Scene.loadNecessaryClass(Scene.java:1729)
	at soot.Scene.loadNecessaryClasses(Scene.java:1741)
	at edu.colorado.plv.fixr.SootHelper.run(SootHelper.java:264)
	at edu.colorado.plv.fixr.extractors.MethodExtractor.extract(MethodExtractor.scala:27)
	at edu.colorado.plv.fixr.tests.regression.TestBug058.$anonfun$new$2(TestBug058.scala:36)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at edu.colorado.plv.fixr.tests.regression.TestBug058.org$scalatest$BeforeAndAfter$$super$runTest(TestBug058.scala:12)
	at org.scalatest.BeforeAndAfter.runTest(BeforeAndAfter.scala:203)
	at org.scalatest.BeforeAndAfter.runTest$(BeforeAndAfter.scala:192)
	at edu.colorado.plv.fixr.tests.regression.TestBug058.runTest(TestBug058.scala:12)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at edu.colorado.plv.fixr.tests.regression.TestBug058.org$scalatest$BeforeAndAfter$$super$run(TestBug058.scala:12)
	at org.scalatest.BeforeAndAfter.run(BeforeAndAfter.scala:258)
	at org.scalatest.BeforeAndAfter.run$(BeforeAndAfter.scala:256)
	at edu.colorado.plv.fixr.tests.regression.TestBug058.run(TestBug058.scala:12)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20492
	at soot.JastAddJ.BytecodeParser.parseThisClass(BytecodeParser.java:437)
	at soot.JastAddJ.BytecodeParser.parseTypeDecl(BytecodeParser.java:413)
	at soot.JastAddJ.BytecodeParser.parse(BytecodeParser.java:331)
	at soot.JastAddJ.BytecodeParser.read(BytecodeParser.java:27)
	at soot.JastAddJ.PathPart.getCompilationUnit(PathPart.java:87)
	... 126 more
```

**Comment by smover** [comment]
The 3 tests fails because they read directly source code and you're probably using java 8 or higher.

Running soot from source code using recent java versions in soot does not work and the problem seems not solved: https://github.com/sable/soot/issues/394

Those tests fail for that reason.
